# Generated by Django 5.2.4 on 2025-07-22 11:44

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('specie', models.CharField(blank=True, choices=[('aedes_aegypti', 'Mosquito del dengue'), ('aedes_albopictus', 'Mosquito tigre'), ('culex_pipiens', 'Mosquito común'), ('aedes_japonicus', 'Mosquito japonés')], max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='observations/images/')),
            ],
            options={
                'verbose_name': 'Observation',
                'verbose_name_plural': 'Observations',
            },
        ),
        migrations.CreateModel(
            name='IdentificationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('specie', models.CharField(blank=True, choices=[('aedes_aegypti', 'Mosquito del dengue'), ('aedes_albopictus', 'Mosquito tigre'), ('culex_pipiens', 'Mosquito común'), ('aedes_japonicus', 'Mosquito japonés')], max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='observations/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task_type', models.CharField(choices=[('biologist', 'Biologo'), ('ai', 'AI')], default='ai', max_length=50)),
                ('annotations', models.TextField(blank=True, null=True)),
                ('identified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to=settings.AUTH_USER_MODEL)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identification_tasks', to='mosquito_app.observation')),
            ],
            options={
                'verbose_name': 'Identification Task',
                'verbose_name_plural': 'Identification Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
